services:
  alfarobi_ws:
    image: alfarobi_ws
    container_name: alfarobi_ws
    #devices:
      #- /dev/ttyUSB0:/dev/ttyUSB0
    volumes:
      #- ./src:/home/alfarobi/alfarobi_ws/src
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - QT_X11_NO_MITSHM=1
      - DISPLAY=:0
    ipc: "host"
