services:
  alfarobi_ws:
    image: alfarobi_ws
    container_name: alfarobi_ws
    privileged: true
    volumes:
      - ./src:/home/altair/alfarobi_ws/src
    environment:
      - QT_X11_NO_MITSHM=1
      - DISPLAY=:0
    ipc: "host"
    network: "host"
